config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root 'welcome#index'
  resources :projects
  resources :emails
  match '/about', to: 'welcome#about', via: 'get'
  match '/contact', to: 'welcome#contact', via: 'get'
  match '/loading', to: 'emails#loading', via: 'get'
  match '/search', to: 'emails#search', via: 'get'
  match '/search_date', to: 'emails#search_date', via: 'get'
  match '/send_mail', to: 'welcome#send_mail', via: 'post'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if user_signed_in?
      @user = current_user
    end
  end

  def about
  end

  def contact
  end

  def send_mail
    # name = params[:message][:name]
    # email = params[:message][:email]
    # body = params[:message][:comments]
    puts params[:message]
    if params[:message][:name].empty?
      redirect_to contact_path, alert: "A name is required."
    elsif params[:message][:email].empty?
      redirect_to contact_path, alert: "An email is required."
    else
      WelcomeMailer.contact_email(mail_params).deliver
      redirect_to root_path, notice: 'Message sent'
    end
  end

  private

    def mail_params
      params.require(:message).permit(:name, :email, :comments)
    end
  
end

app/views/welcome/about.html.erb
<h2>About</h2>

app/views/welcome/contact.html.erb
<h2>Contact</h2>
<div class="container">
  <%= form_tag send_mail_path, :novalidate => "novalidate" do %>
    <div class="form-horizontal">
      <div class="form-group">
        <%= label_tag 'name', 'Name', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= text_field_tag "message[name]", nil, class: 'form-control', placeholder: 'Your Name', required: true %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag 'email', 'Email', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= email_field_tag "message[email]", nil, class: 'form-control', placeholder: 'Your Email Address', required: true %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag 'comments', 'Comments', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= text_area_tag "message[comments]", nil, class: 'form-control', rows: 4, placeholder: 'Comments...' %>
        </div>
      </div>
      <%= submit_tag nil, class: 'btn btn-info pull-right' %>
    </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<% if user_signed_in? %>

  <div class= "row">
    <div class = "col-sm-3">
      <%= image_tag current_user.image, class: "img-responsive img-circle" %>
    </div>
    <div class = "col-sm-6">
      <h2><%= current_user.name %></h2>
      <%= link_to "delete user account", "/users", method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: current_user.name %>
    </div>
  </div>
  <% current_user.projects.each do |project| %>

    <h3><%= link_to project.name, project_path(project.id) %> 
      <small><%= "#{project.description}" %> 
        <span class="badge"><%= "#{project.emails.size}" %></span>
      </small>
    </h3>

    <%= link_to "delete project", project, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: project.name %><br/>
  <% end %>

    <h3><%= link_to 'Create New Project', new_project_path, class: "btn btn-large btn-primary" %></h3>
<% else %>

      <div class="jumbotron">
        <h1>Emailysis</h1>
        <p class="lead">Do you know what's in the box?</p>
        <p>developing custom structures for your email.</p>
        <p><%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2), class: "btn btn-large btn-primary" %></p>
      </div>

      <div class="row marketing">

          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>


      </div>

<% end %>