config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root 'welcome#index'
  resources :projects
  resources :emails
  match '/about', to: 'welcome#about', via: 'get'
  match '/contact', to: 'welcome#contact', via: 'get'
  match '/loading', to: 'emails#loading', via: 'get'
  match '/search', to: 'emails#search', via: 'get'
  match '/search_date', to: 'emails#search_date', via: 'get'
  match '/send_mail', to: 'welcome#send_mail', via: 'post'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :emails, :dependent => :destroy

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]


  def index
    @projects = current_user.projects.all
  end



  def show

    session[:project] = @project.id
    if !@project.emails.empty?

        @inbox = @project.emails.order(sent_at: :desc).where folder: "inbox"
        @sent = @project.emails.order(sent_at: :desc).where folder: "sent"

        @inbox_date_array = []
        @sent_date_array = []
        @sender_array = []
        @to_array = []
        @links = []
        
        ## --- Inbox range and start date
        @start_date = @inbox.first
        @end_date = @inbox.last
        @start = @start_date.sent_at
        @end = @end_date.sent_at
        @inbox_date_difference = (@start.to_date - @end.to_date).to_i
        @start_year = @end.to_time.strftime('%Y')
        @start_month = @end.to_time.strftime('%m')
        @start_month = @start_month.to_i
        @start_month -= 1
        @start_day = @end.to_time.strftime('%d')

        ## --- Sent range and start date
        @sent_start= @sent.first
        @sent_end= @sent.last
        @sent_start_date = @sent_start.sent_at.to_date
        @sent_end_date = @sent_end.sent_at.to_date
        @sent_date_difference = (((@sent_end_date - @sent_start_date)%12)+2).to_i
        @sent_start_year = @sent_start_date.to_time.strftime('%Y')
        @sent_start_month = @sent_start_date.to_time.strftime('%m')
        @sent_start_month = @sent_start_month.to_i
        @sent_start_month -= 1
        @sent_start_day = @sent_start_date.to_time.strftime('%d')

      @inbox.each do |info|

        x = info.sent_at.to_datetime
        x = x.to_time.to_i
        @inbox_date_array << x

        y = info.from
        y.gsub("\\[.*?\\] ", "")
        @sender_array << y

      end

      @sent.each do |info|

        x = info.sent_at.to_datetime
        x = x.to_time.to_i
        @sent_date_array << x

        y = info.to
        @to_array << y

        y = y.split( /, */ )
        y.each do |link|

          @links << { source: info.from, target: link, group: info.sent_at }

        end

        # @forced_layout[:links].each do |link|
        #   @forced_layout[:nodes] << { name: link[:source] }
        #   @forced_layout[:nodes] << { name: link[:target] }
        # end

      end

      @inbox_date_count = Email.email_count(@inbox_date_array)
      @sent_date_count = Email.email_count(@sent_date_array)
      @sender_count = Email.sender_count(@sender_array)
      @to_count = Email.sender_count(@to_array)


      @inbox = @inbox.order(:sent_at).reverse_order
      @sent = @sent.order(:sent_at).reverse_order
      @inbox = @inbox.paginate(page: params[:page], :per_page => 20)
      @sent = @sent.paginate(page: params[:page], :per_page => 20)
      
    end 
    # respond_to do |format|
    #   format.html
    #   format.json { render json: @forced_layout.to_json }
    # end
  end



  def new
    @project = current_user.projects.new
  end

  def create
    @project = current_user.projects.new(project_params)
    if @project.save
      flash[:notice] = "New project created."
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def destroy
    @project.destroy
    flash[:notice] = "Project deleted."
    redirect_to root_path
  end

  private

    def project_params
      params.require(:project).permit(:name, :description)
    end

    def set_project
      @project = current_user.projects.find params[:id]
    end

end

app/views/projects/index.html.erb
<h1>Current Projects:</h1>
<% if @projects.nil? %>
<h2>You do not have any projects.  Please create a new project.</h2>
<% else %>
  <% @projects.each do |project| %>
    <h3><%= link_to project.name, project_path(project.id) %> <small><%= "#{project.description}" %></small></h3>
  <% end %>
<% end %>
<h3><%= link_to 'Create New Project', new_project_path, class: "btn btn-large btn-primary" %></h3>

app/views/projects/new.html.erb
<% if @project.errors.any? %>
  <ul>
  <% @project.errors.full_messages.each do |msg| %>
    <li><%= "#{msg}" %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for @project do |f| %>
<div class="form-horizontal">
  <div class="form-group">
    <%= f.label :name, "Project Name:", class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :name, class: "form-control", placeholder: "Project Name" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, "Project description:", class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_area :description, class: "form-control", placeholder: "Project description" %>
    </div>
  </div>

  <%= f.submit "Submit", class: "btn btn-default pull-right" %>
</div>
<% end %>

app/views/projects/show.html.erb
<h1><%= "#{@project.name}" %> <small><%= "#{@project.description}" %></small></h1>

<% if @project.emails.empty? %>

  <p>No data associated with project.</p>
  <h3><%= link_to 'Get Email', new_email_path, class: "btn btn-large btn-primary" %></h3>

<% else %>

<%= javascript_tag "var d = #{@inbox_date_count.to_json}
                    var e = #{@sent_date_count.to_json}
                    var f = #{@sender_count.to_json}
                    var g = #{@to_count.to_json}
                    var inbox_date_range = #{@inbox_date_difference}
                    var sent_date_range = #{@sent_date_difference}" %>

<!-- <form class="form-horizontal" role="form"> -->
  <div class="form-group">
   
    <%= form_tag('/search/', method: 'get') do %>
      <div class="col-sm-4">
        <%= text_field_tag :q, params[:q], class: "form-control", placeholder: "Search Email" %>
      </div>
        <%= submit_tag 'Search', class: "btn btn-default" %>
    <% end %>
  </div>
<!-- </form> -->

  <h3>Inbox</h3>
  <div id="inbox-map"></div>

<script type="text/javascript">
  var cal = new CalHeatMap();
  cal.init({ 
  itemSelector: "#inbox-map",
  domain: "day",
  subDomain: "hour",
  data: d,
  start: new Date(<%= "#{@start_year}, #{@start_month}, #{@start_day}" %>),
  cellSize: 10,
  range: inbox_date_range,
  tooltip: true,
  legend: [1, 4, 6, 8],
  legendColors: ["#efefef", "steelblue"],
  onClick: function(date, nb) {
    $("#inbox-onClick-placeholder").html("You just clicked <br/>on <b><a href ='/search_date/'" +
      date + ">"+parse(date)+"</b> <br/>with <b>" +
      (nb === null ? "unknown" : nb) + "</b> items"
    );
  }
  });
</script>
  <div id = "inbox-onClick-placeholder"></div>


  <h3>Sent Box</h3>
  <div id="sent-map"></div>

<script type="text/javascript">
  var cal = new CalHeatMap();
  cal.init({ 
  itemSelector: "#sent-map",
  domain: "month",
  subDomain: "day",
  data: e,
  start: new Date(<%= "#{@sent_start_year}, #{@sent_start_month}, #{@sent_start_day}" %>),
  cellSize: 10,
  range: sent_date_range,
  tooltip: true,
  legend: [1, 4, 6, 8],
  legendColors: ["#efefef", "steelblue"],
  onClick: function(date, nb) {
    $("#sent-onClick-placeholder").html("You just clicked <br/>on <b>" +
      date + "</b> <br/>with <b>" +
      (nb === null ? "unknown" : nb) + "</b> items<br/>"
    );
  }
  });
</script>

<div id = "sent-onClick-placeholder"></div>



  <div id = "graph"></div>


<script>

var margin = {top: 20, right: 20, bottom: 250, left: 20},
    width = 800 - margin.left - margin.right,
    height = 700 - margin.top - margin.bottom;
 
var x = d3.scale.ordinal()
    .rangeRoundBands([0, width], .1);
 
var y = d3.scale.linear()
    .range([height, 0]);
 
var color = d3.scale.linear()
    .domain([0,100])
    .range(["#efefef", "steelblue"])
    .interpolate(d3.interpolateLab);
 
var xAxis = d3.svg.axis()
    .scale(x)
    .orient("bottom");
 
var yAxis = d3.svg.axis()
    .scale(y)
    .orient("left")
    .ticks(10);
 
var svg = d3.select("#graph").append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");
 
var data = d3.entries(f);

  x.domain(data.map(function(d) { return d.key; }));
  y.domain([0, d3.max(data, function(d) { return d.value; })]);
 
  svg.append("g")
      .attr("class", "x axis")
      .attr("transform", "translate(0," + height + ")")
      .call(xAxis)
      .selectAll("text")  
          .style("text-anchor", "end")
          .attr("dx", "-.8em")
          .attr("dy", ".15em")
          .attr("transform", function(d) {
              return "rotate(-90)" 
              });
 
  svg.append("g")
      .attr("class", "y axis")
      .call(yAxis)
    .append("text")
      .attr("transform", "rotate(-90)")
      .attr("y", 6)
      .attr("dy", ".71em")
      .style("text-anchor", "end")
      .text("Frequency");
 
  svg.selectAll(".bar")
      .data(data)
    .enter().append("rect")
      .attr("class", "bar")
      .attr("x", function(d) { return x(d.key); })
      .attr("width", x.rangeBand())
      .attr("y", function(d) { return y(d.value); })
      .attr("height", function(d) { return height - y(d.value); })
      .style("fill", function(d) { return color(d.value); });

  svg.append("text")
        .attr("class", "histogram-title")
        .attr("y", height - 400)
        .attr("x", width - 200)
        .attr("text-anchor", "end")
        .text("Top Senders");

</script>

<% end %>